version: v0.0.1

database:
  host: localhost
  username: gombot
  password: password
  dbname: gombot # TODO: it seems dbname dose not support in pg connection string
  port: 5432
  needMigration: true

requesters:
  - abbasi_mohamad
  - almasi_bi
  - afshin990karimi

approvers:
  - fullName: "محمد عباسی"
    username: abbasi_mohamad


baleToken: "2120196445:Qi8AHAbdMeUR7O6zZRf5relALw32HKOThZlZmrtP" # need to restart after change
gitlabToken: "glpat-RUS-PaP1NdoHYyKF4aqj"

applications:
  - name: "import"
    branch: "rc"
    needToApprove: true
    persianName: "واردات"
  - name: "financial"
    branch: "rc"
    needToApprove: true
    persianName: "مالی"
  - name: "gate"
    branch: "rc"
    needToApprove: true
    persianName: "درب خروج"
  - name: "mdm"
    branch: "rc"
    needToApprove: true
    persianName: "اطلاعات پایه"
  - name: "component"
    branch: "rc"
    needToApprove: false
    persianName: "کامپوننت های پایه"
  - name: "my-project"
    branch: "master"
    needToApprove: false
    persianName: "گمبات"
