version: v0.0.1
requesters:
  - abbasi_mohamad
  - almasi_bi
approvers:
  - abbasi_mohama
rollback_permission:
  - alaki
# need to restart after change
token: "480176318:kAUadsCw1DlURmwGVni4SytzL38Zp58TrNUC6XGx"
microservices:
  - name: "import"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"
  - name: "financial"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"
  - name: "gate"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"