version: v0.0.1
requesters:
  - abbasi_mohamad
  - almasi_bi
  - afshin990karimi
approvers:
  - abbasi_mohamad
rollback_permission:
  - alaki
# need to restart after change
token: ""
microservices:
  - name: "import"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"
  - name: "financial"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"
  - name: "gate"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"
  - name: "mdm"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"