version: v0.0.1
database:
  host: localhost
  username: gombot
  password: password
  dbname: gombot # TODO: it seems dbname dose not support in pg connection string
  port: 5432
  needMigration: true
requesters:
  - abbasi_mohamad
  - almasi_bi
  - afshin990karimi
approvers:
  - abbasi_mohamad
rollback_permission:
  - alaki
# need to restart after change
token: "2120196445:Qi8AHAbdMeUR7O6zZRf5relALw32HKOThZlZmrtP"
microservices:
  - name: "import"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"
  - name: "financial"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"
  - name: "gate"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"
  - name: "mdm"
    gitlab_url: "https://code.irica.ir"
    branch: "rc"